# Generated by Django 4.1.7 on 2023-02-28 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Note'},
        ),
    ]
